version: 2.0
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: hugomods/hugo:exts-0.124.1
    steps:
      - run: 'apk update'
      - run: 'apk add openssh-client'
      - run: 'eval $(ssh-agent -s)'
      - add_ssh_keys:
          fingerprints:
            - "70:19:81:46:7b:d3:c9:76:71:b9:87:f6:ff:59:9e:b2"
      - run: 'mkdir -p ~/.ssh'
      - run: 'chmod 700 ~/.ssh'
      - run: 'echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts'
      - run: 'chmod 644 ~/.ssh/known_hosts'
      - checkout
      - run: 'hugo version'
      - run: 'hugo -b https://www.gnuradio.org/ --minify --noTimes'
      - run: 'echo $(date +%Y.%m.%d)'
      - run: 'tar -cz public | ssh $SSH_USER@$SSH_HOST "mkdir -p /www/$(date +%Y.%m.%d); cd /www/$(date +%Y.%m.%d); tar --strip-components=1 -xz; rm /www/live; cd /www; ln -sf $(date +%Y.%m.%d) live;"'
